import { USE_AUTH, USE_PDF_EXPORT, USE_REAL_EMAIL, USE_REAL_SMS, USE_STORAGE, USE_SUPABASE, USE_SUPABASE_CLIENTS, USE_SUPABASE_CONTRACTS, USE_SUPABASE_ESTIMATES, USE_SUPABASE_LEADS, USE_SUPABASE_PAYMENTS, USE_SUPABASE_PROJECTS, USE_SUPABASE_SETTINGS } from './backendConfig'

export const featureFlags = {
  USE_SUPABASE,
  USE_SUPABASE_SETTINGS,
  USE_SUPABASE_CLIENTS,
  USE_SUPABASE_LEADS,
  USE_SUPABASE_PROJECTS,
  USE_SUPABASE_ESTIMATES,
  USE_SUPABASE_CONTRACTS,
  USE_SUPABASE_PAYMENTS,
  USE_STORAGE,
  USE_AUTH,
  USE_REAL_EMAIL,
  USE_REAL_SMS,
  USE_PDF_EXPORT,
}

export const featureFlagOrder = [
  'USE_SUPABASE',
  'USE_SUPABASE_SETTINGS',
  'USE_SUPABASE_CLIENTS',
  'USE_SUPABASE_LEADS',
  'USE_SUPABASE_PROJECTS',
  'USE_SUPABASE_ESTIMATES',
  'USE_SUPABASE_CONTRACTS',
  'USE_SUPABASE_PAYMENTS',
  'USE_STORAGE',
  'USE_AUTH',
  'USE_REAL_EMAIL',
  'USE_REAL_SMS',
  'USE_PDF_EXPORT',
]
